import Head from "next/head";
import Auth_Slider from "../../../components/auth-slider";

export default function ForgotPassword() {
  return (
    <>
      <Head>
        <title>Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="py-12">
          <div className="mx-auto max-w-[1200px] w-full px-4 flex flex-wrap items-center">
              <div className="mb-6 lg:mb-0 lg:pr-20 w-full lg:w-[40%] hidden lg:block">
                  <Auth_Slider />
              </div>
              <div className="w-full lg:w-[60%]">
                  <div className="bg-white shadow-normal border border-teal-400 rounded-[30px] p-10 lg:px-24 min-h-[550px] flex flex-col justify-center">
                      <h1 className="font-medium text-xl md:text-3xl mb-12">
                        Create Password
                      </h1>
                      <form>
                        <div className="mb-6">
                          <label htmlFor="newpassword" className="font-medium mb-2 leading-none inline-block">New Password</label>
                          <input id="newpassword" type="password" className="w-full rounded-full border-slate-300" />
                        </div>
                        <div className="mb-6">
                          <label htmlFor="confirmnewpassword" className="font-medium mb-2 leading-none inline-block">Confirm New Password</label>
                          <input id="confirmnewpassword" type="password" className="w-full rounded-full border-slate-300" />
                        </div>
                        <div className="flex flex-wrap items-center justify-between md:flex-row flex-col">
                          <button type="submit" className="bg-gradient-to-r from-[#6D27F9] to-[#9F09FB] text-white font-bold rounded-full py-2.5 px-6 md:min-w-[200px] transition-all hover:from-[#391188] hover:to-[#391188]">
                            Submit
                          </button>
                        </div>
                      </form>
                  </div>
              </div>
          </div>
        </section>
      </main>
    </>
  );
}
