import Head from 'next/head'

export default function SignIn() {
    return (
    <>
    <Head>
        <title>Auth Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    Auth
    </>
    )
}    